extends Object
class_name DollGesture

const Cocky = "Cocky"
const Dismiss = "Dismiss"
const FuckOff = "FuckOff"
const HappyHand = "HappyHand"
const HeadGesture = "HeadGesture"
const HeadGestureShort = "HeadGestureShort"
const HeadNod = "HeadNod"
const HeadNodHard = "HeadNodHard"
const HeadNodLong = "HeadNodLong"
const HeadNodSarcastic = "HeadNodSarcastic"
const HeadShake = "HeadShake"
const HeadShakeAnnoyed = "HeadShakeAnnoyed"
const HeadShakeLong = "HeadShakeLong"
const LookAway = "LookAway"
const PetHigh = "PetHigh"
const PetLow = "PetLow"
const SexyThinking = "SexyThinking"
const ShrugAngry = "ShrugAngry"
const Sigh = "Sigh"
const Talking1Hand = "Talking1Hand"
const Talking2Hands = "Talking2Hands"
const TalkingLong = "TalkingLong"
const Wave = "Wave"
const Whatever = "Whatever"
const DisplaceTop = "DisplaceTop"
const DisplaceTopUndo = "DisplaceTopUndo"
const DisplaceBra = "DisplaceBra"
const DisplaceBraUndo = "DisplaceBraUndo"
const DisplaceShorts = "DisplaceShorts"
const DisplaceShortsUndo = "DisplaceShortsUndo"
const DisplacePanties = "DisplacePanties"
const DisplacePantiesUndo = "DisplacePantiesUndo"
