extends Object
class_name CharOption

const name = "charName"
const lastName = "lastName"
const gender = "gender"
const species = "species"
const bodySize = "bodySize"
const thickness = "thickness"
const chubbyness = "chubbyness"
const buttSize = "buttSize"
const smoothBody = "smoothBody"
const muscles = "muscles"
const pregnantTest = "pregnantTest"
const voice = "voice"
const walkAnim = "walkAnim"
const idleAnim = "idleAnim"
const idlePose = "idlePose"
const poseArms = "poseArms"
const skinTypes = "skinTypes"
